### ISSUE TITLE
Codes not working

### ISSUE THREAD

**Issue by loxe77** [Minty-Meeo/Pikmin-1-Randomizer-Gecko#2]
Whenever I start up the game, it says "Action Replay Error: Master Code and Write CCXXXXXX not implemented (randomizer) Master Codes are not needed. Do not use master codes." The randomizer doesn't work. Please help idk what to do

**Comment by nstbayless** [comment]
I'm not an expert, but I believe these are gecko codes, not action replay codes. You should place these codes in the gecko codes tab.

**Comment by Minty-Meeo** [comment]
https://github.com/Minty-Meeo/Pikmin-1-Randomizer-Gecko#playing-in-dolphin-emulator
