### ISSUE TITLE
Can not get 29th part Chronos Reactor part due to flower missing

### ISSUE THREAD

**Issue by OfficialCwiggy** [Minty-Meeo/Pikmin-1-Randomizer-Gecko#5]
On The Distant Spring the RNG causes the flower to sometimes not be there. You cannot get the 29th part without using glitches if there is no yellow flower.
![image](https://github.com/user-attachments/assets/4ceb56fc-aad0-4b81-b4c6-fde294feefca)

**Comment by Minty-Meeo** [comment]
This is a result of the simplistic nature of the Gecko Code Randomizer, but is fairly simple to work around.  By throwing your Yellow Pikmin up onto the boundary wall to the right, you can use a large group of Blue Pikmin on the lower level combined with C-Stick swarming to navigate the Yellow Pikmin to the other side of the water with zero casualties.  Alternatively, an out-of-bounds trick found in speedruns can be used to get this ship part entirely without Yellow Pikmin.  I've also seen some people use careful momentum throwing to get Yellow Pikmin onto the middle island, but that's way more effort than the first workaround I suggested.

This Randomizer's development will not continue in its current form, so I'm afraid nothing will be done to change this.
